# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectAuthor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='membership.Member'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectMajor',
            field=models.ManyToManyField(to='membership.Major'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectSkills',
            field=models.ManyToManyField(to='membership.Skill'),
        ),
    ]
