# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20170208_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='major',
            new_name='majors',
        ),
    ]
