# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20170319_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectMajor',
            field=models.ManyToManyField(blank=True, to='membership.Major'),
        ),
    ]
