# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20170412_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Profile',
        ),
    ]
