# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20170412_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectDatePosted',
            field=models.DateField(default=datetime.datetime(2017, 4, 14, 18, 17, 41, 33664)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='majors',
            field=models.ManyToManyField(blank=True, to='membership.Major'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='membership.Skill'),
        ),
    ]
