# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20170414_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDatePosted',
            field=models.DateField(default=datetime.datetime(2017, 4, 14, 18, 29, 46, 92201, tzinfo=utc)),
        ),
    ]
