# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20170414_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDatePosted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
