# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_auto_20170414_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='postDate',
            field=models.DateField(auto_now=True),
        ),
    ]
