# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_project_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectBeginDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectEndDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
